### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by KeithTt** [smpio/kube-browser#23]
kube version: 1.8.4

I deploy kubernator like this:
```
# cat kubernator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernator
  name: kubernator
  namespace: kubernator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernator
  labels:
    k8s-app: kubernator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernator
  namespace: kubernator

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kubernator
  name: kubernator
  namespace: kubernator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kubernator
    spec:
      serviceAccountName: kubernator
      containers:
      - image: smpio/kubernator
        imagePullPolicy: IfNotPresent
        name: kubernator
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: kubernator
  name: kubernator
  namespace: kubernator
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30211
  selector:
    run: kubernator
```

When I access the UI, I get some 401 errors:

![image](https://user-images.githubusercontent.com/15189954/34475584-5e4f8bd4-efc8-11e7-9196-4af0f29b3785.png)

And the logs seems normal:
```
# kubectl logs -f kubernator-547df67847-wcdd7 -n kubernator
132.1.1.3 - shengyongp [02/Jan/2018:06:16:15 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "220.181.190.66"
132.1.1.3 - shengyongp [02/Jan/2018:06:16:16 +0000] "GET /favicon.png HTTP/1.1" 200 24528 "https://kubernator.oupeng.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "220.181.190.66"
132.1.1.3 - shengyongp [02/Jan/2018:06:16:22 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "220.181.190.66"
132.1.1.3 - shengyongp [02/Jan/2018:06:16:22 +0000] "GET /favicon.png HTTP/1.1" 200 24528 "https://kubernator.oupeng.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "220.181.190.66"
132.1.1.3 - shengyongp [02/Jan/2018:06:17:51 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "220.181.190.66"
132.1.1.3 - shengyongp [02/Jan/2018:06:17:52 +0000] "GET /favicon.png HTTP/1.1" 200 24528 "https://kubernator.oupeng.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" "220.181.190.66"
```
