### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by KeithTt** [smpio/kube-browser#24]
kube version: 1.8.4

I deploy kubernator like this:
```
# cat kubernator.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kubernator
  name: kubernator
  namespace: kubernator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernator
  labels:
    k8s-app: kubernator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernator
  namespace: kubernator

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kubernator
  name: kubernator
  namespace: kubernator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kubernator
    spec:
      serviceAccountName: kubernator
      containers:
      - image: smpio/kubernator
        imagePullPolicy: IfNotPresent
        name: kubernator
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  labels:
    run: kubernator
  name: kubernator
  namespace: kubernator
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30211
  selector:
    run: kubernator
```

![image](https://user-images.githubusercontent.com/15189954/34736612-86e40156-f5ae-11e7-9e84-b7b9e0f75467.png)
