### ISSUE TITLE
Creating new objects from scratch doesn't work

### ISSUE THREAD

**Issue by nailgun** [smpio/kube-browser#6]
1. Open k8s-browser
2. Click "+"
3. Paste this:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: monitoring
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

4. Shit happened!
