### ISSUE TITLE
Can't create any objects

### ISSUE THREAD

**Issue by nailgun** [smpio/kube-browser#9]
Payload:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: local-hdd
```

Error: https://monosnap.com/file/1TQ7fCoOXadMqNE5RunP0D6fTrCJ5V

But this works with old version (same payload): https://monosnap.com/file/yvEZnj2sN1szuGwqx9qeOxIhtpMoef
